//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Punten_LVL1 { get; set; }
        public Nullable<int> Punten_LVL2 { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string Role { get; set; }
        public int DivisionID { get; set; }
        public int CountryID { get; set; }
        public Nullable<int> BadgeID { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Divisions Divisions { get; set; }
        public virtual Badge Badges { get; set; }
    }
}
